# Generated by Django 3.2.4 on 2021-07-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsapplication', '0004_auto_20210703_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='MachineOperatorStart',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='MachineOperatorStop',
            new_name='stop_datetime',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='MachineOperatorID',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='MachineOperatorTime',
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='mc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ccsapplication.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='operate_time',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
