# Generated by Django 3.2.4 on 2021-07-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsapplication', '0005_auto_20210703_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawTransaction',
            new_name='Transaction',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(default='-', max_length=50)),
                ('date', models.DateField(default=None, null=True)),
                ('operate_time', models.CharField(default='0', max_length=50)),
                ('mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsapplication.machine')),
            ],
        ),
    ]
