# Generated by Django 3.2.4 on 2021-07-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsapplication', '0006_auto_20210703_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shift',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
