# Generated by Django 3.2.4 on 2021-07-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsapplication', '0007_auto_20210705_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='shift',
        ),
    ]
