# Generated by Django 3.2.4 on 2021-08-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsapplication', '0013_machine_exp_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='exp_min',
            new_name='exp_hrs',
        ),
    ]
